language: python

python:
  - "3.6"

install:
  # install latest release version
  # - wget $(wget -qO- https://api.github.com/repos/gohugoio/hugo/releases/latest | sed -r -n '/browser_download_url/{/Linux-64bit.deb/{s@[^:]*:[[:space:]]*"([^"]*)".*@\1@g;p}}')
  - wget https://github.com/gohugoio/hugo/releases/download/v0.50/hugo_0.50_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - pip install Pygments
  - rm -rf public 2> /dev/null

script:
  - hugo
