title: Blog do Rodrigo
description: Um blog feito com muito carinho!
author: "Rodrigo"

#url: "http://rodrigo54.github.io/"
url: "http://127.0.0.1:4000"
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: "/index.html"
 - title: Portifolio
   url: /portifolio/home.html
 - title: Sobre
   url: /sobre/home.html
 - title: Contato
   url: /contato/home.html

social:
   github: rodrigo54
   twitter: rodrigo254mix
   facebook: rodrigo54
   email: 5rodrigo@hotmail.com

google_analytics: ""

timezone: America/Fortaleza