[context.production]
  command = "npm run build"
  publish = "public"

[context.deploy-preview]
  command = "npm run "
  publish = "public"

[context.branch-deploy]
  command = "npm run "
  publish = "public"
